vich_uploader:
    db_driver: orm

    mappings:
       evenements:
           uri_prefix: '/uploads/images/evenements'
           upload_destination: '%kernel.project_dir%/public/uploads/images/evenements'
           namer: Vich\UploaderBundle\Naming\SmartUniqueNamer

